### ISSUE TITLE
can't compile due to missing native static sasl2 library

### ISSUE THREAD

**Issue by mikelpr** [MaterializeInc/rust-sasl#47]
I've installed cyrus-sasl-devel (openSUSE, fedora; libsasl2-dev on ubuntu) which provides pkg-config --libs libsasl2 and also tried making a symlink from /usr/lib64/pkgconfig/libsasl2.pc to /usr/lib64/pkgconfig/sasl2.pc thinking that may be it but I'm still getting

`error: could not find native static library ``sasl2``, perhaps an -L flag is missing?`

maybe static here is key but in that case shouldn't cargo be building it? pkg-config --libs-only-L does not return anything, and I know of no distros that package static sasl. fedora, openSUSE and ubuntu certainly don't.

**Comment by awaltert** [comment]
Hi, I'm also facing exactly this problem, too.

Context: For one project,  I want to statically compile `rdkafka` which depends on `sasl2`. They provide certain features flags in order to enable static compilation. One of this flags is `gssapi-vendored` which will pull in `sasl2-sys` into the compilation process. 

Unfortunately I found no way in order to make the compilation succeed because of error mentioned in this issue.

This dependency is the last  one which prevents the static compilation. This situation forces me to use a dynamic linking instead. This is not ideal because relying on dynamic linking also increases the complexity for the build pipeline, deployments, etc. too.

@mikelpr Have you been able to make any progress on this topic?

**Comment by JanZerebecki** [comment]
Mikel talked to me on Matrix about this. Initially found while compiling https://github.com/vectordotdev/vector . Mikel confirmed that the vendored and gssapi-vendored feature when used in an empty cargo project break both in the same way on OpenSUSE but work on Fedora 36. Without those features it also works on OpenSUSE.

I assume that means something from one of the sasl rpms has something that confuses the sasl-sys build.rs script.

**Comment by JanZerebecki** [comment]
Which probably means there is an error somewhere in the sasl2-sys build.rs file.

**Comment by JanZerebecki** [comment]
This might fix it: https://github.com/MaterializeInc/rust-sasl/pull/49

**Comment by awaltert** [comment]
Hi @JanZerebecki, thanks for looking into the issue. The reasoning makes perfect sense to me.
I will checkout the PR, test it on my machine and provide feedback afterwards :smile:

**Comment by mikelpr** [comment]
so stuck in limbo? :(

**Comment by yuzhichang** [comment]
@awaltert @JanZerebecki  #49 change is great but not enough. I've added  a comment with another change to the PR.
